CC=gcc
LD=ld
ASM=nasm

CFLAGS=-ffreestanding -m32 -c -fno-stack-protector -fno-builtin -fno-pic -fno-pie -I.
LDFLAGS=-m elf_i386 -T linker/linker.ld -nostdlib

KERNEL_OBJ = kernel/kernel.o kernel/init.o kernel/setup.o kernel/login.o kernel/shell.o kernel/game.o kernel/ata.o kernel/ahci.o kernel/store.o kernel/idt.o kernel/elf.o kernel/exec.o kernel/linux.o kernel/doom.o arch/x86/linux_asm.o

# ELF32 command binaries.  Every source in bin/ is compiled with
# plain host gcc (-m32, freestanding, ET_REL) into its own standalone
# ELF32 binary in home/bin/, then embedded in the kernel image (via
# home.tar) as /bin/<name>.o, where the shell finds it at boot.
# tools/tcc/build-tcc.sh builds the TinyCC compiler the same way:
# home/bin/tcc.o -> /bin/tcc.o, so `tcc` is just another command.
# The only toolchain the build needs is gcc, nasm and ld.
BIN_SRC = $(wildcard bin/*.c)
BIN_OUT = $(BIN_SRC:bin/%.c=home/bin/%.o)
TCC_HDRS = $(wildcard tools/tcc/std-include/*.h tools/tcc/std-include/sys/*.h)
TCC_BUILD_SCRIPT ?= build-tcc.sh
TCC_SRC = tools/tcc/build-tcc.sh tools/tcc/build-tcc-arm64.sh tools/tcc/tanja-libc.c tools/tcc/tanja-libc.h \
          tools/tcc/tanja-tcc-main.c tools/tcc/install-headers.sh $(TCC_HDRS) \
          $(wildcard tools/tcc/tinycc/*.c) $(wildcard tools/tcc/tinycc/*.h) \
          $(wildcard tools/tcc/tanja-libc-include/*.h)
HOME_OBJ = home_tar.o


all: arch/x86/boot/tanja-base

BUILD_TS := $(shell date +%s)

/include/build_id.h: $(wildcard kernel/*.c) $(wildcard fs/*.c) $(BIN_SRC) $(wildcard include/*.h) home.tar
	@echo "[GEN] /include/build_id.h (build $(BUILD_TS))"
	@echo "/* Auto-generated by the build - do not edit or commit. */" > $@
	@echo "#define TANJA_BUILD_ID_LO $(BUILD_TS)u" >> $@
	@echo "#define TANJA_BUILD_ID_HI 0u" >> $@

.PHONY: home_image
home_image: home_tar.o

home/bin:
	mkdir -p home/bin

BIN_CFLAGS = -m32 -ffreestanding -fno-stack-protector -fno-builtin \
             -fno-pic -fno-pie -fno-common \
             -fno-asynchronous-unwind-tables \
             -Wno-builtin-declaration-mismatch -I include -I .

home/bin/%.o: bin/%.c include/tanja.h include/fs.h include/utf8.h | home/bin
	@echo "[CC] bin/$*.c (ELF32)"
	$(CC) $(BIN_CFLAGS) -c $< -o $@

# TinyCC builds with its own script (it needs per-file -D flags);
# install-headers.sh refreshes home/include/ from the header sets.
tools/tcc/tcc.o: $(TCC_SRC)
	@if [ -f tools/tcc/tinycc/tcc.c ]; then \
		echo "[TCC] building TinyCC (freestanding i386 object)"; \
		(cd tools/tcc && ./$(TCC_BUILD_SCRIPT)); \
		(cd tools/tcc && ./install-headers.sh); \
	else \
		echo "[TCC] tinycc source tree not present; using bundled tools/tcc/tcc.o"; \
		test -f tools/tcc/tcc.o; \
	fi

home/bin/tcc.o: tools/tcc/tcc.o | home/bin
	cp $< $@

home.tar: $(shell find home -type f -o -type d 2>/dev/null | grep -v '^home/bin/') $(BIN_OUT) home/bin/tcc.o
	@echo "[TAR] Packing home/ (binaries as /bin, headers as /include)"
	rm -rf .home-stage
	tar --format=ustar -cf $@ -C home .

home_tar.o: home.tar
	@echo "[OBJ] Embedding home/"
	$(LD) -r -b binary -m elf_i386 -o $@ $<

kernel/%.o: kernel/%.c
	@echo "[CC] kernel/$(notdir $<)"
	$(CC) $(CFLAGS) -o $@ $<


kernel/store.o: kernel/store.c include/build_id.h
	@echo "[CC] kernel/store.c"
	$(CC) $(CFLAGS) -o kernel/store.o kernel/store.c


arch/x86/idt_asm.o: arch/x86/idt_asm.asm
	@echo "[ASM] idt_asm.asm"
	$(ASM) -f elf32 arch/x86/idt_asm.asm -o arch/x86/idt_asm.o


fs/fs.o: fs/fs.c
	@echo "[CC] fs/fs.c"
	$(CC) $(CFLAGS) -o fs/fs.o fs/fs.c


arch/x86/boot/boot.o: arch/x86/boot/boot.asm | arch/x86/boot
	@echo "[ASM] boot.asm"
	$(ASM) -f elf32 arch/x86/boot/boot.asm -o arch/x86/boot/boot.o


arch/x86/linux_asm.o: arch/x86/linux_asm.asm
	@echo "[ASM] linux_asm.asm"
	$(ASM) -f elf32 arch/x86/linux_asm.asm -o arch/x86/linux_asm.o


# DOOM: built in, like tcc
# The Doom program (ports/doom) and its IWAD are linked into the kernel image
# as binary blobs (a program this size cannot live in the 320 KiB-per-file
# filesystem); kernel/doom.c runs them via the `doom` shell command.
DOOM_OBJ  = ports/doom/build/doom_elf.o ports/doom/build/doom_wad.o
DOOM_DEPS = $(wildcard ports/doom/*.c ports/doom/Makefile ports/doom/engine/* ports/doom/include/* ports/doom/include/sys/* ports/doom/wad/*)

$(DOOM_OBJ): $(DOOM_DEPS)
	@echo "[DOOM] building ports/doom"
	@$(MAKE) --no-print-directory -C ports/doom CC="$(CC)" LD="$(LD)" ARCH_FLAGS="$(filter -m32,$(CFLAGS))" \
		$(if $(DOOM_WAD_SRC),DOOM_WAD_SRC="$(DOOM_WAD_SRC)") \
		$(if $(DOOM_IWAD_NAME),DOOM_IWAD_NAME="$(DOOM_IWAD_NAME)")

arch/x86/boot/tanja-base: arch/x86/boot/boot.o arch/x86/idt_asm.o $(KERNEL_OBJ) fs/fs.o $(HOME_OBJ) $(DOOM_OBJ) | arch/x86/boot
	@echo "[LD] Linking..."
	$(LD) $(LDFLAGS) -o arch/x86/boot/tanja-base \
		arch/x86/boot/boot.o \
		arch/x86/idt_asm.o \
		$(KERNEL_OBJ) \
		fs/fs.o \
		$(HOME_OBJ) \
		$(DOOM_OBJ)

	@echo
	@echo "[INFO] TanjaOS image ready at arch/x86/boot/tanja-base"
	@echo


iso:
	mkdir arch/x86/boot/iso_root/
	mkdir arch/x86/boot/iso_root/boot/
	mkdir arch/x86/boot/iso_root/boot/grub/
	mv arch/x86/boot/tanja-base arch/x86/boot/iso_root/boot/kernel.elf
	touch arch/x86/boot/iso_root/boot/grub/grub.cfg
	echo "menuentry "USR/UX" {" > arch/x86/boot/iso_root/boot/grub/grub.cfg
	echo "    multiboot /boot/kernel.elf" >> arch/x86/boot/iso_root/boot/grub/grub.cfg
	echo "    boot" >> arch/x86/boot/iso_root/boot/grub/grub.cfg
	echo "}" >> arch/x86/boot/iso_root/boot/grub/grub.cfg
	grub-mkrescue -o usr_ux.iso arch/x86/boot/iso_root

clean:
	rm -rf kernel/*.o fs/*.o tools/tcc/build
	rm -rf arch/x86/boot/*.o arch/x86/boot/tanja-base
	$(MAKE) -C ports/doom clean
	rm -rf arch/x86/*.o home.tar home_tar.o *.o
	rm -rf arch/x86/boot/iso_root/
	rm -rf home/bin .home-stage
	#rm -rf include/build_id.h

.PHONY: all clean home_image doom iso

doom: all
