#!/bin/sh

set -e
cd "$(dirname "$0")"

SRC=tinycc
CFLAGS="-m32 -ffreestanding -fno-builtin -nostdlib -fno-pic -fno-pie \
 -fno-stack-protector -fno-strict-aliasing -Wno-unused-result -Wno-declaration-after-statement \
 -Os -g0 -I tanja-libc-include -I $SRC -DTCC_TARGET_I386 \
 -DCONFIG_TCC_SYSINCLUDEPATHS='\"/include\"'"

# tcc.c is the all-in-one build (ONE_SOURCE): it #includes libtcc.c ->
# tccpp/tccgen/tccelf/tccdbg/tccasm/tccrun/i386-* and tcctools.c.
# So we compile tcc.c alone, plus our libc shim and the entry wrapper.
compile() {
    src="$1"; extra="$2"
    o="build/$(echo "$src" | tr '/' '_')"
    o="${o%.c}.o"
    echo "[CC] $src $extra"
    eval i686-linux-gnu-gcc $CFLAGS $extra -c "$src" -o "$o"
    OBJS="$OBJS $o"
}

rm -f build/*.o
mkdir -p build
OBJS=""

if [ ! -f "$SRC/tcc.c" ]; then
    echo "error: $SRC/tcc.c not found."
    echo "Clone tinycc first:"
    echo "    cd $(dirname "$0") && git clone https://github.com/TinyCC/tinycc.git"
    exit 1
fi

# --- prepare generated headers tinycc's own Makefile would normally build ---
# (upstream tinycc.c needs config.h and tccdefs_.h, both produced by tools
# in tinycc's Makefile; we generate them here with the *host* compiler so a
# plain `git clone` of tinycc drops in and builds with no extra steps)
if [ ! -f "$SRC/config.h" ]; then
    echo "[GEN] $SRC/config.h"
    cat > "$SRC/config.h" <<CFG
/* Generated by build-tcc: minimal, target-agnostic (see tcc.h for what's used) */
#define TCC_VERSION "0.9.28rc"
#define CONFIG_TCC_PREDEFS 1
CFG
fi
if [ ! -f "$SRC/tccdefs_.h" ]; then
    # c2str only needs to run once, on THIS machine, to turn tccdefs.h into
    # a string table - it has nothing to do with the i386 target, so any
    # native compiler works (the i686 cross-compiler produces an i386
    # binary, which can't run on an arm64 host).
    HOSTCC=""
    for c in cc gcc clang; do
        command -v "$c" >/dev/null 2>&1 && { HOSTCC="$c"; break; }
    done
    if [ -z "$HOSTCC" ]; then
        echo "error: no native C compiler found (cc/gcc/clang) to build tinycc's"
        echo "c2str host tool (a one-time step, unrelated to the i386 cross-build)."
        echo "Install one, e.g.:"
        echo "    sudo apt install gcc"
        exit 1
    fi
    echo "[GEN] $SRC/tccdefs_.h (via host c2str, built with $HOSTCC)"
    "$HOSTCC" -DC2STR "$SRC/conftest.c" -o build/c2str
    (cd "$SRC" && ../build/c2str include/tccdefs.h tccdefs_.h)
fi


compile "$SRC/tcc.c" "-Dmain=tcc_main_real"
compile "tanja-libc.c" ""
compile "tanja-tcc-main.c" ""

echo "[LD -r] merging -> tcc.o"
i686-linux-gnu-ld -m elf_i386 -r -o tcc.o $OBJS

echo "[SIZE]"
size tcc.o | tail -1
ls -la tcc.o

echo "[UNDEFINED SYMBOLS] (must all be kernel exports)"
nm -u tcc.o | sed 's/ *U //' | sort -u > build/undefined.txt
cat build/undefined.txt

echo "[INSTALL] -> ../../home/bin/tcc.o (embedded as /bin/tcc.o)"
mkdir -p ../../home/bin
cp tcc.o ../../home/bin/tcc.o
